language: rust
os: linux
dist: bionic

cache:
  directories:
    - /home/travis/.cargo
    - ./target/

before_cache:
  - rm -rf /home/travis/.cargo/registry

jobs:
  include:
    - before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check

    - script:
        - cargo build --verbose

    - os:
        - windows
      script:
        - cargo build --verbose

    - before_script:
        - sudo apt-get install -y python3-pip python3-setuptools tree
        - pip3 install --upgrade pip
        - pip3 install -r ./utils/requirements.txt --progress-bar off
        - python3 ./utils/prepare_models.py
      script:
        - cargo test -- --skip test_sbert_encode_attention --skip test_distilroberta_for_classification_rust_tokenizers_sentencepiece --skip test_rust_tokenizers_sentencepiece
